### ISSUE TITLE
Parameter 2, defined

### ISSUE THREAD

**Issue by Asteliks** [kobuki/RFM69OOK#3]
There seems to be something wrong with the example OOKDrumer sketch 

![image](https://user-images.githubusercontent.com/62251475/89028139-0d193900-d32c-11ea-98f1-88e5f5d1fc11.png)

**Comment by kobuki** [comment]
Did you install the library?

**Comment by Asteliks** [comment]
If by that you mean put it in the libraries folder in Arduino path than yes

**Comment by kobuki** [comment]
It still looks like the lib is not installed properly. The compiler doesn't find the main class or `#define` of the lib. Maybe try restarting the IDE or something. Closing as it's definitely not a library issue.

**Comment by Asteliks** [comment]
Basically what I'm trying to do is to receive and later on clone my garage door remote (HORMANN HSM4-868). I'm running the RFM69 with an ESP32 the idea is to make an homekit device that receives the gate opening signal and can send the gate opening/closing signal

**Comment by ant-thomas** [comment]
I'm getting this error when trying to compile for ESP8266. Is this expected?
