### ISSUE TITLE
clarification for instructions for DIO2

### ISSUE THREAD

**Issue by donwade** [kobuki/RFM69OOK#4]
Some rfm69 people have DIO1 going to D3, I believe you are asking for DIO2 to go to D3 correct?
I assume your using DIO2 for reading the raw data bits and are making use of D3's interrupt abilities?
Just wondering if I can move DIO2 to D4. Not sure.

**Comment by kobuki** [comment]
The required info is in the readme and it works for the specified chips. For other chips this of course may vary. You can use any free pin on your chip to handle DIOx pads on the RFM board.

**Comment by donwade** [comment]
Thank you
